name: Push to S3

on:
  workflow_dispatch:

jobs:
  train-finetune-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./api.py
          destination: s3://gpt2-finance-model/api
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          aws_region: ap-south-1
